version: "3"

tasks:
  format-yaml:
    internal: true
    cmds:
      - npx prettier {{ .DIR }} --write

  format-node-configs:
    cmds:
      - task: format-yaml
        vars:
          DIR: ./cluster/main/talos/

  generate-node-configs:
    cmds:
      - talhelper genconfig

  bootstrap-talos-node:
    cmds:
      - talosctl bootstrap
        --talosconfig=./cluster/shared/talosconfig
        --insecure
        # --cluster highglade \
        # --nodes 10.30.0.160 \

  export-kubeconfig:
    internal: true
    cmds:
      - talosctl kubeconfig ./highglade-kubeconfig
        -n {{ .NODE }}
        -e {{ .NODE }}

  export-kubeconfig-s1:
    cmds:
      - task: export-kubeconfig
        vars:
          NODE: 10.30.0.161

  try-all:
    cmds:
      - talosctl apply-config -n 10.30.0.161 -e 10.30.0.161 -f clusterconfig/highglade-cluster-sentinel-1.yaml --talosconfig ./clusterconfig/talosconfig --mode=try
      - talosctl apply-config -n 10.30.0.162 -e 10.30.0.162 -f clusterconfig/highglade-cluster-sentinel-2.yaml --talosconfig ./clusterconfig/talosconfig --mode=try
      - talosctl apply-config -n 10.30.0.163 -e 10.30.0.163 -f clusterconfig/highglade-cluster-sentinel-3.yaml --talosconfig ./clusterconfig/talosconfig --mode=try
      - talosctl apply-config -n 10.30.0.164 -e 10.30.0.164 -f clusterconfig/highglade-cluster-sentinel-4.yaml --talosconfig ./clusterconfig/talosconfig --mode=try
      - talosctl apply-config -n 10.30.0.165 -e 10.30.0.165 -f clusterconfig/highglade-cluster-sentinel-5.yaml --talosconfig ./clusterconfig/talosconfig --mode=try
      - talosctl apply-config -n 10.30.0.166 -e 10.30.0.166 -f clusterconfig/highglade-cluster-sentinel-6.yaml --talosconfig ./clusterconfig/talosconfig --mode=try

  update-control-points:
    cmds:
      - talosctl apply-config -n 10.30.0.161 -e 10.30.0.161 -f clusterconfig/highglade-cluster-sentinel-1.yaml --talosconfig ./clusterconfig/talosconfig
      - talosctl apply-config -n 10.30.0.162 -e 10.30.0.162 -f clusterconfig/highglade-cluster-sentinel-2.yaml --talosconfig ./clusterconfig/talosconfig
      - talosctl apply-config -n 10.30.0.163 -e 10.30.0.163 -f clusterconfig/highglade-cluster-sentinel-3.yaml --talosconfig ./clusterconfig/talosconfig

  update-machine-configs-insecure:
    cmds:
      - talosctl apply-config -n 10.30.0.161 -e 10.30.0.161 -f clusterconfig/highglade-cluster-sentinel-1.yaml --talosconfig ./clusterconfig/talosconfig --insecure
      - talosctl apply-config -n 10.30.0.162 -e 10.30.0.162 -f clusterconfig/highglade-cluster-sentinel-2.yaml --talosconfig ./clusterconfig/talosconfig --insecure
      - talosctl apply-config -n 10.30.0.163 -e 10.30.0.163 -f clusterconfig/highglade-cluster-sentinel-3.yaml --talosconfig ./clusterconfig/talosconfig --insecure

  update-all:
    cmds:
      - task: update-control-points
      - task: update-workers

  update-workers:
    cmds:
      - talosctl apply-config -n 10.30.0.164 -e 10.30.0.164 -f clusterconfig/highglade-cluster-sentinel-4.yaml --talosconfig ./clusterconfig/talosconfig
      - talosctl apply-config -n 10.30.0.165 -e 10.30.0.165 -f clusterconfig/highglade-cluster-sentinel-5.yaml --talosconfig ./clusterconfig/talosconfig
      - talosctl apply-config -n 10.30.0.166 -e 10.30.0.166 -f clusterconfig/highglade-cluster-sentinel-6.yaml --talosconfig ./clusterconfig/talosconfig

  update-workers-insecure:
    cmds:
      - talosctl apply-config -n 10.30.0.164 -e 10.30.0.164 -f clusterconfig/highglade-cluster-sentinel-4.yaml --talosconfig ./clusterconfig/talosconfig --insecure
      - talosctl apply-config -n 10.30.0.165 -e 10.30.0.165 -f clusterconfig/highglade-cluster-sentinel-5.yaml --talosconfig ./clusterconfig/talosconfig --insecure
      - talosctl apply-config -n 10.30.0.166 -e 10.30.0.166 -f clusterconfig/highglade-cluster-sentinel-6.yaml --talosconfig ./clusterconfig/talosconfig --insecure
