version: "3"

tasks:
  format-yaml:
    internal: true
    cmds:
      - npx prettier {{ .DIR }} --write

  format-node-configs:
    cmds:
      - task: format-yaml
        vars:
          DIR: ./cluster/main/talos/

  generate-node-configs:
    cmds:
      - talhelper genconfig

  bootstrap-talos-node:
    cmds:
      - talosctl bootstrap
        --talosconfig=./cluster/shared/talosconfig
        --insecure
        # --cluster highglade \
        # --nodes 10.30.0.160 \

  export-kubeconfig:
    internal: true
    cmds:
      - talosctl kubeconfig ./highglade-kubeconfig
        -n {{ .NODE }}
        -e {{ .NODE }}

  export-kubeconfig-s1:
    cmds:
      - task: export-kubeconfig
        vars:
          NODE: 10.30.0.161

  # Generic apply configuration command (reusable for multiple nodes)
  apply-config:
    internal: true
    cmds:
      - talosctl apply-config
        -n {{ .NODE }}
        -e {{ .ENDPOINT }}
        -f {{ .CONFIG_FILE }}
        --talosconfig ./clusterconfig/talosconfig
        {{ .CLI_ARGS }}

  # Apply config for control plane nodes (sentinel-1, sentinel-2, sentinel-3)
  update-control-points:
    cmds:
      - task: apply-config
        vars:
          NODE: 10.30.0.161
          ENDPOINT: 10.30.0.161
          CONFIG_FILE: clusterconfig/highglade-cluster-sentinel-1.yaml
          # CLI_ARGS: --mode=reboot
      - task: apply-config
        vars:
          NODE: 10.30.0.162
          ENDPOINT: 10.30.0.162
          CONFIG_FILE: clusterconfig/highglade-cluster-sentinel-2.yaml
          # CLI_ARGS: --mode=reboot
      - task: apply-config
        vars:
          NODE: 10.30.0.163
          ENDPOINT: 10.30.0.163
          CONFIG_FILE: clusterconfig/highglade-cluster-sentinel-3.yaml
          # CLI_ARGS: --mode=reboot
          #
  # Apply config for worker nodes (sentinel-4, sentinel-5, sentinel-6)
  update-workers:
    cmds:
      - task: apply-config
        vars:
          NODE: 10.30.0.164
          ENDPOINT: 10.30.0.164
          CONFIG_FILE: clusterconfig/highglade-cluster-sentinel-4.yaml
          # CLI_ARGS: --mode=reboot
      - task: apply-config
        vars:
          NODE: 10.30.0.165
          ENDPOINT: 10.30.0.165
          CONFIG_FILE: clusterconfig/highglade-cluster-sentinel-5.yaml
          # CLI_ARGS: --mode=reboot
      - task: apply-config
        vars:
          NODE: 10.30.0.166
          ENDPOINT: 10.30.0.166
          CONFIG_FILE: clusterconfig/highglade-cluster-sentinel-6.yaml
          # CLI_ARGS: --mode=reboot

  try-all:
    cmds:
      - task: update-control-points --mode=try
      - task: update-workers --mode=try

  update-all:
    cmds:
      - task: update-control-points
      - task: update-workers

  update-all-insecure:
    cmds:
      - talhelper gencommand apply --extra-flags

  install-helm-repos:
    cmds:
      - helm repo add traefik https://traefik.github.io/charts
      - helm repo add cilium https://helm.cilium.io/

  deploy-traefik:
    cmds:
      - kubectl kustomize --enable-helm ./kustomize/apps/traefik/overlay/prod | kubectl apply -f -

  deploy-cilium:
    cmds:
      - kubectl kustomize --enable-helm ./kustomize/network/cilium | kubectl apply -f -

      # helm v3 until kubectl is updated:
      # kustomize build --enable-helm ./kustomize/network/cilium --helm-command /opt/homebrew/opt/helm@3/bin/helm | kubectl apply -f -
  deploy-openebs:
    cmds:
      - helm install openebs --namespace openebs openebs/openebs --set zfs-localpv.zfsNode.encrKeysDir=/var/openebs/keys
