apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-rolebinding
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: network-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-role
