kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: small-openebs-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
